session_name: base
start_directory: '~'
windows:
- window_name: home
  focus: 'true'
- window_name: ctracks
  layout: 3425,197x67,0,0[197x46,0,0{117x46,0,0,1,79x46,118,0,4},197x20,0,47,5]
  start_directory: '~/workspace/climbtracks'
  panes:
    - focus: true
    -
    -
- window_name: ansible-lab
  layout: main-vertical
  start_directory: '~/workspace/ansible-lab'
  panes:
    -
    -
