# /home/yevgeny/.config/tmuxinator/base.yml

name: base
on_project_start: $(sleep 1 && tmux select-layout -t base:2 63b6,204x63,0,0[204x49,0,0{121x49,0,0,1,82x49,122,0,4},204x13,0,50,5]) &
root: ~/

windows:
  - home:
  - climbtracks:
      layout: 63b6,204x63,0,0[204x49,0,0{121x49,0,0,1,82x49,122,0,4},204x13,0,50,5]
      root: ~/workspace/climbtracks
      panes:
        - Vim:
          - cd api
          - pipenv shell
        - #empty
        - #empty
  - ansible-lab:
      root: ~/workspace/ansible-lab
      layout: main-vertical
      panes:
        - vim
        - #empty
  - 340b:
      root: ~/workspace/340b
      layout: main-vertical
      panes:
        - jupyter:
          - poetry shell
        - #empty
